# TCL File Generated by Component Editor 15.1
# Sat Mar 26 19:55:53 CET 2016
# DO NOT MODIFY


# 
# qei "qei" v1.0
# Csibi 2016.03.26.19:55:53
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module qei
# 
set_module_property DESCRIPTION ""
set_module_property NAME qei
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR Csibi
set_module_property DISPLAY_NAME qei
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL quad
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file quad.v VERILOG PATH output_files/quad.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point digit
# 
add_interface digit nios_custom_instruction end
set_interface_property digit clockCycle 0
set_interface_property digit operands 2
set_interface_property digit ENABLED true
set_interface_property digit EXPORT_OF ""
set_interface_property digit PORT_NAME_MAP ""
set_interface_property digit CMSIS_SVD_VARIABLES ""
set_interface_property digit SVD_ADDRESS_GROUP ""

add_interface_port digit quadA a Input 5
add_interface_port digit quadB c Input 1
add_interface_port digit count result Output 32

